defaults: &defaults
  adapter: mysql2
  encoding: utf8
  pool: 25
  reaping_frequency: 20
  username: root
  password: ram
  socket: /var/run/mysqld/mysqld.sock

development:
  database: spotmyarena_development
  <<: *defaults

test:
  database: myappone_test
  <<: *defaults

production:
  database: spotmyarena_production
  <<: *defaults