defaults: &defaults
  adapter: postgresql
  encoding: unicode
  pool: 20
  username: postgres
  password: ram
  host: localhost
  port: 5432

development:
  database: myappone_development
  <<: *defaults

test:
  database: myappone_test
  <<: *defaults

production:
  database: myappone_production
  <<: *defaults
